FROM python:3.9

RUN addgroup appgroup
RUN adduser --disabled-password --home '/home/appuser' --ingroup appgroup appuser

WORKDIR /data

RUN mkdir /data/tmp/
RUN chown -R appuser:appgroup /data/tmp

USER appuser

WORKDIR /data/code/

RUN git clone https://github.com/nasa-jpl/tos2ca-data-dictionaries.git ./data-dictionaries

COPY requirements.txt .
COPY tos2ca_data_driver.py .

COPY .netrc /home/appuser/.netrc

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install git+https://github.com/nasa-jpl/tos2ca-anomaly-detection.git@dev --no-cache-dir
RUN pip install git+https://github.com/nasa-jpl/tos2ca-aux-geoir.git@dev --no-cache-dir
RUN pip install git+https://github.com/nasa-jpl/tos2ca-fortracc-module.git@dev --no-cache-dir

ENTRYPOINT ["python", "tos2ca_data_driver.py"]
